{
 "title": "GoLang Metrics (for Prometheus Operator) Copy",
 "description": "Golang Application Runtime metrics",
 "time": { "from": "2024-11-08T19:31:15.921Z", "to": "2024-11-08T19:32:40.280Z" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(go_goroutines, namespace)"
   },
   {
    "name": "pod",
    "label": "pod",
    "query": "label_values(go_goroutines{namespace=\"$namespace\"}, pod)"
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(go_goroutines,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "http_response_status_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Memory in Heap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{namespace=\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "heap alloc"
    },
    {
     "expr": "go_memstats_heap_sys_bytes{namespace=\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "heap sys"
    },
    {
     "expr": "go_memstats_heap_idle_bytes{namespace=\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "heap idle"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{namespace=\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "heap inuse"
    },
    {
     "expr": "go_memstats_heap_released_bytes{namespace=\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "heap released"
    }
   ]
  },
  {
   "title": "irate % usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "avg by (instance) (irate(process_cpu_seconds_total{}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Used Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_sys_bytes{namespace=\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Time Request process by src",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(echo_http_request_duration_seconds_sum{handler=\"/\", instance=~\"$instance\"}[$__rate_interval])) by (instance) / sum(rate(echo_http_request_duration_seconds_count{handler=\"/\", instance=~\"$instance\"}[$__rate_interval])) by (instance)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Rate of Objects Allocated",
   "type": "timeseries",
   "description": "shows how many heap objects are allocated. This is a counter value so you can use rate() to objects allocated/s.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(go_memstats_mallocs_total{namespace=\"$namespace\", pod=~\"$pod\"}[1m])",
     "legendFormat": "mallocs rate"
    }
   ]
  },
  {
   "title": "CPU percent usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{instance=~\"$instance\"}[30s])) by (instance)  / 30 * 100 ",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_goroutines{namespace=\"$namespace\", pod=~\"$pod\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory in Off-Heap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_mspan_inuse_bytes{namespace=\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "mspan inuse"
    },
    {
     "expr": "go_memstats_mspan_sys_bytes{namespace=\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "mspan sys"
    },
    {
     "expr": "go_memstats_mcache_inuse_bytes{namespace=\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "mcache inuse"
    },
    {
     "expr": "go_memstats_mcache_sys_bytes{namespace=\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "mcache sys"
    },
    {
     "expr": "go_memstats_buck_hash_sys_bytes{namespace=\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "buck hash sys"
    },
    {
     "expr": "go_memstats_gc_sys_bytes{namespace=\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "gc sys"
    },
    {
     "expr": "go_memstats_other_sys_bytes{namespace=\"$namespace\", pod=~\"$pod\"} - go_memstats_other_sys_bytes{namespace=\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "bytes of memory are used for other runtime allocations {pod={{pod}}}"
    },
    {
     "expr": "go_memstats_next_gc_bytes{namespace=\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "next gc"
    }
   ]
  },
  {
   "title": "GC duration quantile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "go_gc_duration_seconds{namespace=\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Memory in Stack",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_stack_inuse_bytes{namespace=\"$namespace\", pod=~\"$pod\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}} stack inuse"
    },
    {
     "expr": "go_memstats_stack_sys_bytes{namespace=\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "{{instance}} stack sys"
    }
   ]
  },
  {
   "title": "Number of Live Objects",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_memstats_mallocs_total{namespace=\"$namespace\", pod=~\"$pod\", instance=~\"$instance\"} - go_memstats_frees_total{namespace=\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Rates of Allocation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(go_memstats_alloc_bytes_total{namespace=\"$namespace\", pod=~\"$pod\", instance=~\"$instance\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}