name: web-backend
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: studios
      POSTGRES_USER: studios
      POSTGRES_PASSWORD: studios
    ports:
      - "5438:5432"
