// Code generated by mockery v2.46.0. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "ppo/domain"

	dto "ppo/services/dto"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// ISaladInteractor is an autogenerated mock type for the ISaladInteractor type
type ISaladInteractor struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, salad
func (_m *ISaladInteractor) Create(ctx context.Context, salad *domain.Salad) (uuid.UUID, error) {
	ret := _m.Called(ctx, salad)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 uuid.UUID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Salad) (uuid.UUID, error)); ok {
		return rf(ctx, salad)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Salad) uuid.UUID); ok {
		r0 = rf(ctx, salad)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Salad) error); ok {
		r1 = rf(ctx, salad)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteById provides a mock function with given fields: ctx, id
func (_m *ISaladInteractor) DeleteById(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteById")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields: ctx, filter, page
func (_m *ISaladInteractor) GetAll(ctx context.Context, filter *dto.RecipeFilter, page int) ([]*domain.Salad, int, error) {
	ret := _m.Called(ctx, filter, page)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []*domain.Salad
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.RecipeFilter, int) ([]*domain.Salad, int, error)); ok {
		return rf(ctx, filter, page)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dto.RecipeFilter, int) []*domain.Salad); ok {
		r0 = rf(ctx, filter, page)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Salad)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dto.RecipeFilter, int) int); ok {
		r1 = rf(ctx, filter, page)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, *dto.RecipeFilter, int) error); ok {
		r2 = rf(ctx, filter, page)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetAllByUserId provides a mock function with given fields: ctx, id
func (_m *ISaladInteractor) GetAllByUserId(ctx context.Context, id uuid.UUID) ([]*domain.Salad, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetAllByUserId")
	}

	var r0 []*domain.Salad
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*domain.Salad, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*domain.Salad); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Salad)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllRatedByUser provides a mock function with given fields: ctx, userId, page
func (_m *ISaladInteractor) GetAllRatedByUser(ctx context.Context, userId uuid.UUID, page int) ([]*domain.Salad, int, error) {
	ret := _m.Called(ctx, userId, page)

	if len(ret) == 0 {
		panic("no return value specified for GetAllRatedByUser")
	}

	var r0 []*domain.Salad
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int) ([]*domain.Salad, int, error)); ok {
		return rf(ctx, userId, page)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int) []*domain.Salad); ok {
		r0 = rf(ctx, userId, page)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Salad)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int) int); ok {
		r1 = rf(ctx, userId, page)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID, int) error); ok {
		r2 = rf(ctx, userId, page)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetById provides a mock function with given fields: ctx, id
func (_m *ISaladInteractor) GetById(ctx context.Context, id uuid.UUID) (*domain.Salad, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetById")
	}

	var r0 *domain.Salad
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Salad, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Salad); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Salad)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, salad
func (_m *ISaladInteractor) Update(ctx context.Context, salad *domain.Salad) error {
	ret := _m.Called(ctx, salad)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Salad) error); ok {
		r0 = rf(ctx, salad)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewISaladInteractor creates a new instance of ISaladInteractor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewISaladInteractor(t interface {
	mock.TestingT
	Cleanup(func())
}) *ISaladInteractor {
	mock := &ISaladInteractor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
