app:
  name: 'course_project'
  version: 'v0.1'

logger:
  level: 'info'
  file: 'logs.log'

http:
  port: 8081

currentDb:
  db: 'postgres'

database:
  driver: 'postgres'
  host: 'localhost'
  port: 5432
  user: 'user'
  password: 'pass'
  dbname: 'salads'

databaseMysql:
  driver: 'mysql'
  host: 'saladsDB_mysql'
  port: 3306
  user: 'user'
  password: 'pass'
  dbname: 'saladRecipes'

jwt:
  key: '13278sabdjkas1289'