name: Go tests

on: [push]

permissions:
  contents: write


jobs:
  build-and-push-image:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO_NAME }}
          tags: latest
          labels: latest

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  run-unit-tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    container:
      image: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO_NAME }}
      options: --privileged
    steps:
      - name: run-unit-tests
        run:
          dockerd
          cd backend/src/tests
          go test ./e2e_test/ -v -json > testE2e.log
#          go test ./repository_test/ -v -json > testRepository.log
#      - name: Upload service test logs
#        uses: actions/upload-artifact@v4
#        with:
#          name: testService
#          path: testService.log
#          retention-days: 7
#      - name: Upload repository test logs
#        uses: actions/upload-artifact@v4
#        with:
#          name: testService
#          path: testService.log
#          retention-days: 7
      - name: Upload repository test logs
        uses: actions/upload-artifact@v4
        with:
          name: testE2e
          path: testE2e.log
          retention-days: 7



#      - name: Set up Go
#        uses: actions/setup-go@v4
#        with:
#          go-version: '1.22.0'
#
#      - name: Run unit tests
#        run: make ci-unit -i
#
#      - name: Run integration tests
#        run: make ci-integration -i
#
#      - name: Run E2E tests
#        run: make ci-e2e -i
#
#      - name: Processing report data
#        run: make ci-concat-reports
#
#      - name: Load test report history
#        uses: actions/checkout@v3
#        if: always()
#        continue-on-error: true
#        with:
#          ref: gh-pages
#          path: gh-pages
#
#      - name: Build test report
#        uses: simple-elf/allure-report-action@v1.7
#        if: always()
#        with:
#          gh_pages: gh-pages
#          allure_history: allure-history
#          allure_results: allure-results
#
#      - name: Publish test report
#        uses: peaceiris/actions-gh-pages@v3
#        if: always()
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          publish_branch: gh-pages
#          publish_dir: allure-history