# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go tests

on:
  [push]

permissions:
  contents: write

jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: Run tests
    steps:  
      - uses: actions/checkout@v4
  
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.2'
          cache-dependency-path: backend/go.sum

      - name: Install dependencies
        run: cd backend && go mod tidy

      - name: Run unit-service tests
        run: |
          cd backend
          go test -tags=unit_test ./... -v -json > testUnit.log

      - name: Run integration tests
        run: |
          cd backend
          go test -tags=integration_test ./... -v -json > testIntegration.log

      - name: Run e2e tests
        run: |
          cd backend
          go test -tags=e2e_test ./... -v -json > testE2e.log

      - name: Upload unit test logs
        uses: actions/upload-artifact@v4
        continue-on-error: true
        with:
          name: testUnit
          path: backend/testUnit.log
          retention-days: 7

      - name: Upload integration test logs
        continue-on-error: true
        uses: actions/upload-artifact@v4
        with:
          name: testIntegration
          path: backend/testIntegration.log
          retention-days: 7

      - name: Upload e2e test logs
        continue-on-error: true
        uses: actions/upload-artifact@v4
        with:
          name: testE2e
          path: backend/testE2e.log
          retention-days: 7

  make-report:
    needs: run-tests
    name: Make report
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.0'

      - name: Install dependencies
        run:
          cd backend && go mod tidy

      - name: Download unit test log
        uses: actions/download-artifact@v4
        continue-on-error: true
        with:
          name: testUnit

      - name: Download integration test log
        uses: actions/download-artifact@v4
        continue-on-error: true
        with:
          name: testIntegration

      - name: Download e2e test log
        uses: actions/download-artifact@v4
        continue-on-error: true
        with:
          name: testE2e

      - name: Make report
        run: |
          cd backend
          go get -u github.com/vakenbolt/go-test-report/
          go install github.com/vakenbolt/go-test-report/
          touch test.log
          cat testUnit.log >> test.log || true
          cat testIntegration.log >> test.log || true
          cat testE2e.log >> test.log || true
          cat test.log | go-test-report -o report.html

      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: report
          path: backend/report.html
          retention-days: 7